os: linux
  
language: go

go:
  - 1.13.x
  
services:
- docker

script:   
- go test -v ./...
- CGO_ENABLED=0 go build -o demo

- echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin

- docker build -f Dockerfile -t s1910595015/demo:latest ./

- GIT_SHA="$(git rev-parse --short HEAD)"
- docker tag s1910595015/demo:latest s1910595015/demo:$GIT_SHA

- docker push s1910595015/demo:latest
- docker push s1910595015/demo:$GIT_SHA
